language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: dJAxhDPLpXr0NXBcBh92A5YBvwZqLmLbN3W+dpMu9rL1b3XWbTxC3ATbzV55GbyskJZxxQp8Kb1vADQML4xs4qa0/BAuVTV5PqogwIj6rNqaZKR5iyQFoPG20i5OD8QGBGXw8LsEpFjetudzFrrwsYBLgxF4hLue2Y4dDjDdeyl7rhlIEglhLz6vo23Ih8VDorY4BFS1WsTwFmOFH4Noc3BJF7AhUYnsCdRxPkbd9x6qFjboscYb+aq4LL7DsCKG5vMrUjoa2dGy3TsLRw45k1qVBBTEvbOPsUD9RqcTACaseo4JgE0j4k9NeiLiuxkUTqMR/FawGl44ohglJrbikv3+5jcyHfdc4OBC+rTvCS1dzezt+H5nLRuEduHM1sxOmcnN/w1EfGi7ugBV59AVe5Y/BdHzZOVaCZTvYlLHM8ai91/jw4bqzT3eg5VHdfuS/UraK55sjnsODspEOGnYv0HNyQZbehExIMFr8I/XX3aT75AMBsnlPJo17A0zNm39sl1w/IODU59b90hSPBE5/iwnrhI5Urnlxhm8OC9Da4VKQIfYt21Dc3SDlXaAKu3lbolLlkZeZqjxRlWWFXpC+n2lFmo58EbXvfd7aZG6dmi+7zHwzHmQLyhLCtoRObKi2aoQKzYe27El00i6MZLq/dPWG1xvNQGyR8Ru/QPIkJk=
